version: '3'
services:
  contacts-api:
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - mongodb
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - "./data:/data/db"